### ISSUE TITLE
SecureChannel 'monitor' goroutine panics after calling SecureChannel.Close()

### ISSUE THREAD

**Issue by dwhutchison** [gopcua/opcua#119]
I've run across an issue when trying to close and create another SecureChannel inside a client.  After I call Close() on the first instance of a SecureChannel, the program quickly panics due to a nil pointer deference inside `func (s *SecureChannel) monitor(ctx context.Context)`.

I think the issue is this goroutine stays blocked on
`n, err := s.lowerConn.Read(s.rcvBuf)` 
so it never sees that the context finishes and returns cleanly.  Inside the call to close, s.lowerConn gets assigned to nil, resulting in the panic.

Simply commenting out the lowerConn nil assignment in SecureChannel.close() stops this, but I haven't looked to see if there are other impacts of doing so.

**Comment by wmnsk** [comment]
Thank you for reporting the issue.
Yes, I saw the same panic but I haven’t found the best way to fix it.

As you mentioned, blocking in Read and closing the lowerConn looks bad. Let me check the whole behavior further and fix it.

My work will be in the next weekend, so if you find a good fix before that time, please issue a PR 😉
