### ISSUE TITLE
ERROR on	go secChan.monitor(ctx)

### ISSUE THREAD

**Issue by abay94** [gopcua/opcua#129]
Please could you help me on this issue

<img width="963" alt="screenshot 2018-10-30 12 53 26" src="https://user-images.githubusercontent.com/25668394/47701105-f91a4200-dc42-11e8-93a0-ad988a41841a.png">

**Comment by wmnsk** [comment]
This might be due to the unexpected format of a message coming.
Could you share your source code in `main.go` and pcap file if available?

**Comment by abay94** [comment]
Thank you for your response. 
I have just run the gopcua/examples/client/client.go script with changing endpoint.

p.s. I am  a new in golang ( sorry if it is so stupid question)


`// Copyright 2018 gopcua authors. All rights reserved.
// Use of this source code is governed by a MIT-style license that can be
// found in the LICENSE file.

/*
Command client provides a connection establishment of OPC UA Secure Conversation.
*/
package main

import (
	"context"
	"encoding/hex"
	"flag"
	"log"
	"time"

	"github.com/wmnsk/gopcua/datatypes"
	"github.com/wmnsk/gopcua/services"
	"github.com/wmnsk/gopcua/uacp"
	"github.com/wmnsk/gopcua/uasc"
	"github.com/wmnsk/gopcua/utils"
)

func main() {
	var (
		endpoint   = flag.String("endpoint", "opc.tcp://Abays-MacBook-Pro.local:53530/OPCUA/SimulationServer", "OPC UA Endpoint URL")
		payloadHex = flag.String("payload", "ff13", "Payload to send in hex stream format")
	)
	flag.Parse()

	// Create context for UACP to be used by statemachine working background.
	ctx := context.Background()
	ctx, cancel := context.WithCancel(ctx)
	defer cancel()

	// Establish UACP Connection with the Endpoint specified.
	conn, err := uacp.Dial(ctx, *endpoint)
	if err != nil {
		log.Fatal(err)
	}
	defer func() {
		if err := conn.Close(); err != nil {
			log.Fatalf("Failed to shutdown connection: %s", err)
		}
		log.Println("Successfully shutdown connection")
	}()
	log.Printf("Successfully established connection with %v", conn.RemoteEndpoint())

	// Open SecureChannel on top of UACP Connection established above.
	cfg := uasc.NewClientConfigSecurityNone(3333, 3600000)
	secChan, err := uasc.OpenSecureChannel(ctx, conn, cfg, 5*time.Second, 3)
	if err != nil {
		log.Fatal(err)
	}
	defer func() {
		if err := secChan.Close(); err != nil {
			log.Fatalf("Failed to close secure channel: %s", err)
		}
		log.Printf("Successfully closed secure channel with %v", conn.RemoteEndpoint())
	}()
	log.Printf("Successfully opened secure channel with %v", secChan.RemoteEndpoint())

	//Send FindServersRequest to remote Endpoint.
	if err := secChan.FindServersRequest([]string{"ja-JP", "de-DE", "en-US"}, "gopcua-server"); err != nil {
		log.Fatal(err)
	}
	log.Println("Successfully sent FindServersRequest")
	time.Sleep(500 * time.Millisecond)

	// Send GetEndpointsRequest to remote Endpoint.
	if err := secChan.GetEndpointsRequest([]string{"ja-JP", "de-DE", "en-US"}, []string{"gopcua-server"}); err != nil {
		log.Fatal(err)
	}
	log.Println("Successfully sent GetEndpointsRequest")
	time.Sleep(500 * time.Millisecond)

	sessCfg := uasc.NewClientSessionConfig(
		[]string{"en-US"},
		datatypes.NewAnonymousIdentityToken("anonymous"),
	)
	session, err := uasc.CreateSession(ctx, secChan, sessCfg, 3, 5*time.Second)  ////// <<<<<<<<  errrrorrrr
	if err != nil {
		log.Fatal(err)
	}
	defer func() {
		session.Close()
		log.Printf("Successfully closed secure channel with %v", secChan.RemoteEndpoint())
	}()
	log.Printf("Successfully created secure channel with %v", secChan.RemoteEndpoint())

	if err := session.Activate(); err != nil {
		log.Fatal(err)
	}
	log.Printf("Successfully activated secure channel with %v", secChan.RemoteEndpoint())

	if err := session.ReadRequest(
		2000, services.TimestampsToReturnBoth, datatypes.NewReadValueID(
			datatypes.NewNumericNodeID(0, 11111), datatypes.IntegerIDValue, "", 0, "",
		),
	); err != nil {
		log.Fatal(err)
	}
	log.Println("Successfully sent ReadRequest")

	// Send arbitrary payload on top of UASC SecureChannel.
	payload, err := hex.DecodeString(*payloadHex)
	if err != nil {
		log.Fatal(err)
	}
	if _, err := secChan.WriteService(payload); err != nil {
		log.Fatal(err)
	}
	log.Printf("Successfully sent message: %x\n%s", payload, utils.Wireshark(0, payload))
	time.Sleep(500 * time.Millisecond)
}`

**Comment by lishuaia** [comment]
hi abay94
 I have been looking at the code of the block recently. Can I leave a way of communication?

**Comment by wmnsk** [comment]
OK it seems the source code is the same one in `examples` directory.
Then we need to analyze the incoming packets to find out the exact cause. Could you reproduce it in your environment again and share the captured packets?

**Comment by abay94** [comment]
Helllooo! 
Here is my print 
<img width="764" alt="screenshot 2018-10-31 19 38 01" src="https://user-images.githubusercontent.com/25668394/47791822-c2c4eb80-dd44-11e8-9354-9476e073836d.png">

<img width="1437" alt="screenshot 2018-10-31 19 40 38" src="https://user-images.githubusercontent.com/25668394/47791908-fd2e8880-dd44-11e8-83c3-9f525712c401.png">

**Comment by abay94** [comment]
Yes, of course thanks!

**Comment by wmnsk** [comment]
@abay94 
Could you share the packet captures, not the source codes and console outputs?
Also please paste the source codes directly in your comment instead of putting screenshots when you need to do that next time.

**Comment by abay94** [comment]
Sorry, I do not know where can I see the captured packets. If the next msg is not a packet ( it is decoded part of attribute of SucureChannel:rcvBuf, 3 times) 

`**1)** &{MessageType: 5197902, ChunkType: 70, MessageSize: 135, Payload: 2f000000687474703a2f2f6f7063666f756e646174696f6e2e6f72672f55412f5365637572697479506f6c696379234e6f6e65ffffffffffffffffe8030000050d00000100c1010000000000000000010000000000000000ffffffff00000000000000240000000100000000e4fd2b7970d40180ee360000000000, SecurityPolicyURI: 47, http://opcfoundation.org/UA/SecurityPolicy#None, SenderCertificate: &{-1 []}, ReceiverCertificateThumbprint: &{-1 []}, Payload: e8030000050d00000100c1010000000000000000010000000000000000ffffffff00000000000000240000000100000000e4fd2b7970d40180ee360000000000 <nil> SequenceNumber: 1000, RequestID: 3333, Payload: 0100c1010000000000000000010000000000000000ffffffff00000000000000240000000100000000e4fd2b7970d40180ee360000000000 2185-07-21 23:34:33.709551616 +0000 UTC, 1, 0, [0], &{-1 []}, &{0, 0 0}, 00000000240000000100000000e4fd2b7970d40180ee360000000000}

**2)** &{MessageType: 5067591, ChunkType: 70, MessageSize: 56, Payload: 01000000e9030000050d00000100a90160cefe2b7970d4010200000000000000000000000000000000000000, <nil> TokenID: 1, Payload: e9030000050d00000100a90160cefe2b7970d4010200000000000000000000000000000000000000 SequenceNumber: 1001, RequestID: 3333, Payload: 0100a90160cefe2b7970d4010200000000000000000000000000000000000000 2018-10-30 17:51:23.206 +0000 UTC, 2, 0, [0], &{0 []}, &{0, 0 0}, 00000000}

**3)** &{MessageType: 5067591, ChunkType: 70, MessageSize: 56, Payload: 01000000ea030000050d00000100af0120524c2c7970d401030000000000000000ffffffff00000000000000, <nil> TokenID: 1, Payload: ea030000050d00000100af0120524c2c7970d401030000000000000000ffffffff00000000000000 SequenceNumber: 1002, RequestID: 3333, Payload: 0100af0120524c2c7970d401030000000000000000ffffffff00000000000000 2018-10-30 17:51:23.714 +0000 UTC, 3, 0, [0], &{-1 []}, &{0, 0 0}, 00000000} `

**Comment by lishuaia** [comment]
hi @abay94 
Are you using the go language to write the opcua client, and then read the data from the server? Can you give me your mail box? Let's talk about it.

**Comment by wmnsk** [comment]
From the logs you pasted, gopcua tried to decode `GetEndpointsResponse` with "Good(0x00000000)" `ServiceResult` but it has zero-sized `Endpoints`. So this might be the problem with our decoder causing crash when decoding it(Decoders are not so robust in the current implementation).

* If you don't need to send `GetEndpointsRequest` to your server, delete the lines related to it.
* If you need it, please capture packets and attach here to debug. Packets can be captured with Wireshark or tcpdump.

**Comment by abay94** [comment]
OK thanks!!
