### ISSUE TITLE
I get ua.BrowseResponse on ua.PublishRequest

### ISSUE THREAD

**Issue by ghost** [gopcua/opcua#185]
Goroutine 1: Sending PublishRequest and waiting for response
Goroutine 2: Sending BrowseRequest and waiting for response
Goroutine 1: Received ua.BrowseResponse
Goroutine 2: waiting

Seems like related to SequenceNumber in #184

**Comment by magiconair** [comment]
Can you check whether you still see that with the fix from #185?

**Comment by ghost** [comment]
Yeah, still getting `invalid response: *ua.BrowseResponse`

**Comment by alexbrdn** [comment]
I also get a response of a wrong type from a different goroutine with the current master

**Comment by magiconair** [comment]
Can you try running this with `OPCUA_DEBUG="debug packet"` ?

**Comment by magiconair** [comment]
This might provide some additional info on where to look or where we should add more debug messages.

**Comment by alexbrdn** [comment]
I think there's no need for that. I believe I have found the culprit. Let me prepare a Pull Request and we'll discuss it there.

**Comment by magiconair** [comment]
@wsnotify can you verify that this fixes your problem as well?

**Comment by ghost** [comment]
@magiconair Looks like it helped.
