### ISSUE TITLE
How to browse folder's in a NodeClass?

### ISSUE THREAD

**Issue by cngobd** [gopcua/opcua#191]
@magiconair I want to browse all available folder's  belong to  a  NodeClass,
my NodeClass index in Prosys Opc UA simulation server :
NodeClass :
       NamespaceIndex:       0
       NamespaceURI:          http://opcfoundation.org/UA/
       IdentifierType :            Numeric
       Identifier:                    85
How to config the browse.go in examples.  Please?

**Comment by magiconair** [comment]
The example in `browse.go` is a starting point but not a generic example for browsing since the OPC/UA data model is too complex. You can use the recursive `browseChildren` function as a starting point but how you filter and what you output depends on your specific use case.

**Comment by cngobd** [comment]
@magiconair Thank you for your help, now I want to browse all folders organized by root when I connect to the Prosys OpcUA server , is there any functions can implement it?
please

**Comment by magiconair** [comment]
The code in `browse.go` should be a starting point but you have to find our yourself on how to do this. I don't have an example for this.

**Comment by cngobd** [comment]
@magiconair which functions should I use to get the "user access level" of a node?
Please

**Comment by magiconair** [comment]
@769139671 I've created #199 with the methods for `AccessLevel` and `UserAccessLevel`. I'll wait for some comments from the other developers but then we can merge this.

**Comment by cngobd** [comment]
@magiconair Thank you!

**Comment by magiconair** [comment]
I've just merged #199
