### ISSUE TITLE
SecureChannel doesn't close cleanly

### ISSUE THREAD

**Issue by alexbrdn** [gopcua/opcua#226]
After #211, calling `SecureChannel.Close()` always results in [this error](https://github.com/gopcua/opcua/pull/211/files#diff-3974e78f8d605b659904cde0bc4caa98R540) being written to debug output:
> debug: failed to close transport connection: close tcp 10.0.75.1:59181->10.0.75.1:53530: use of closed network connection

**Comment by dwhutchison** [comment]
My bad.  Please verify that #229 fixes this.

**Comment by magiconair** [comment]
Ah. I was too quick. @alexbrdn please reopen if this is not fixed
