### ISSUE TITLE
config_test.go fails on Windows

### ISSUE THREAD

**Issue by alexbrdn** [gopcua/opcua#228]
`config_test.go` hardcodes filenames like "/tmp/gopcua-test-cert.der" instead of using `ioutil.TestFile()` or `ioutil.TestDir()`. Naturally, the test fails on Windows.

**Comment by alexbrdn** [comment]
Yeah, I know, who uses Windows anyways, right? Don't judge me! ;)

**Comment by magiconair** [comment]
Sorry for being lazy :(
