### ISSUE TITLE
How to access a node by StringNodeId ?

### ISSUE THREAD

**Issue by sdghchj** [gopcua/opcua#236]
Is there any way to access a node by path of DisplayName?

for example:

ua.NewStringNodeId(2,"demo_led.temperature")

![image](https://user-images.githubusercontent.com/20944466/60857287-86834c80-a23c-11e9-848f-44cf71cb36fe.png)

**Comment by magiconair** [comment]
We don’t have a method to find a node by display name. You can browse for the browse name but that is not as simple as using `ns=2;i=2`

**Comment by magiconair** [comment]
I think adding support for `TranslateBrowsePathsToNodeIds` might address this. Do you want to send a PR?

**Comment by sdghchj** [comment]
> I think adding support for `TranslateBrowsePathsToNodeIds` might address this. Do you want to send a PR?

Yes, check PR, please
