### ISSUE TITLE
Variant.Value() does not return the value

### ISSUE THREAD

**Issue by sdghchj** [gopcua/opcua#246]
a member named 'value' in ua.Variant type，but 'Value' returned in Value method.
`
type Variant struct {
	
	value interface{}
}
`

`
func (m *Variant) Value() interface{} {
	return m.Value
}
`

**Comment by kung-foo** [comment]
ah yes, https://github.com/gopcua/opcua/blob/master/ua/variant.go#L101-L103 should return `m.value`.

**Comment by magiconair** [comment]
Fixed in v0.1.4

**Comment by sdghchj** [comment]
> Fixed in v0.1.4

OK,thanks

**Comment by kung-foo** [comment]
you're too fast @magiconair https://github.com/Intelecy/opcua/commit/bee1a8c187da5e54431dd3c3d6322fdf90e7814a :)

**Comment by magiconair** [comment]
@kung-foo sorry :'( You can have the next bug :)
