### ISSUE TITLE
potential memory exhaustion in ua.Variant decoder

### ISSUE THREAD

**Issue by kung-foo** [gopcua/opcua#248]
https://github.com/gopcua/opcua/blob/v0.1.4/ua/variant.go#L123-L127

`Variant.Decode` calls `reflect.MakeSlice` with an unchecked value. There is a potential (either malicious or accidental) for memory exhaustion.

**Comment by magiconair** [comment]
What should we use as an upper bound?

—
Frank Schröder

**Comment by kung-foo** [comment]
maybe something like `var MaxVariantArrayLength = 0xffff`? And if a user wants to override it, they can do it via:

```golang
func init() {
    ua.MaxVariantArrayLength = 0x1000000
}
```

**Comment by magiconair** [comment]
Sounds reasonable. I still need to limit recursion as well. Want to send a PR?

**Comment by magiconair** [comment]
Closed by #249
