### ISSUE TITLE
monitor.Subscription does not allow changing of monitoring parameters (queue size, sampling interval)

### ISSUE THREAD

**Issue by blunghamer** [gopcua/opcua#268]
`Subscription.AddNodeIDs` does directly lookup `NewMonitoredItemCreateRequestWithDefaults` which contains standard settings for `QueueSize` = 10 and `SamplingInterval` = 0.0 and applies those to the subscription. 

I am no go expert but this behaviour cannot be override. `AddNodeIDs` should contain extra arguments to supply the monitoring parameters in the method signature.

Are pull requests welcome on this one?

**Comment by magiconair** [comment]
Pull requests are always welcome.

**Comment by bbergshaven** [comment]
Added a [PR](https://github.com/gopcua/opcua/pull/345) to address this.
