### ISSUE TITLE
Is there a way to get list of object NodeIDs from the server?

### ISSUE THREAD

**Issue by zergon321** [gopcua/opcua#274]
I have an OPC UA simulation server with this object hierarchy:

![Screenshot from 2019-09-18 13-45-54](https://user-images.githubusercontent.com/22347549/65142376-3df5c580-da1b-11e9-862e-d503a52d5abe.png)

Is it possible to get the list of simulation objects' NodeIDs?

**Comment by magiconair** [comment]
Check the `example/browse/browse.go` code. That does that recursively.

**Comment by kung-foo** [comment]
You'll need to wait for https://github.com/gopcua/opcua/pull/284 to land since it looks like you are using Prosys.

**Comment by magiconair** [comment]
Just merged it.
