### ISSUE TITLE
ua.ParseNodeID fails to parse strings without namespace

### ISSUE THREAD

**Issue by kung-foo** [gopcua/opcua#285]
`ua.ParseNodeID` should handle a string like `i=2253`.

From Part 6 / 5.3.1.10:

> The NamespaceIndex formatted as a base 10 number.
> If the index is 0 then the entire 'ns=0;' clause shall be omitted.

Invalid test:
https://github.com/gopcua/opcua/blob/v0.1.5/ua/node_id_test.go#L134

**Comment by magiconair** [comment]
What was I thinking?
