### ISSUE TITLE
ua.GUID.String() does not zero pad correctly

### ISSUE THREAD

**Issue by kung-foo** [gopcua/opcua#287]
`NewGUIDNodeID(0, "AAAABBBB-0001-EEFF-0101-0123456789AB").String() != "g=AAAABBBB-0001-EEFF-0101-012345678900"`

**Comment by magiconair** [comment]
:/

**Comment by kung-foo** [comment]
pr incoming

**Comment by magiconair** [comment]
bracing

**Comment by kung-foo** [comment]
pizza first :)
