### ISSUE TITLE
StatusBadDecodingError (0x80070000) when trying to browse nodes

### ISSUE THREAD

**Issue by zergon321** [gopcua/opcua#294]
I use **Prosys OPC UA Simulation Server-4.0.0-105**. I wanted to get the list of the nodes located in the `Simulation` folder:
![Screenshot from 2019-10-02 21-23-52](https://user-images.githubusercontent.com/22347549/66071000-03337780-e55b-11e9-84db-16fdcd5d05a1.png)
so I used `opcua/examples/browse` with the ID of the `Simulation` node: `ns=3;s=85/0:Simulation`, but it always returns the next output:

> browse children: Decoding halted because of invalid data in the stream. StatusBadDecodingError (0x80070000)
exit status 1

I tried to use different browse levels and `sudo` command, but nothing changed. It works good with single simulation parameters, like `ns=3;s=Counter`, but not with "folders".
How to make it show the list of the nodes instead of the error?
Full log with `debug` option enabled:

> debug: Connect to opc.tcp://localhost:53530/OPCUA/SimulationServer
debug: conn 1: start HEL/ACK handshake
debug: conn 1: sent HELF with 80 bytes
debug: conn 1: recv ACKF with 28 bytes
debug: conn 1: server has no chunk limit. Using 512
debug: conn 1: server has no message size limit. Using 2097152
debug: conn 1: recv &uacp.Acknowledge{Version:0x0, ReceiveBufSize:0x2004, SendBufSize:0x2004, MaxMessageSize:0x200000, MaxChunkCount:0x200}
debug: uasc 1/1: send *ua.OpenSecureChannelRequest with 132 bytes
debug: conn 1: recv OPNF with 135 bytes
debug: uasc: OPN Request
debug: uasc 1/1: set secure channel id to 48
debug: uasc 1/1: recv OPNF with 135 bytes
debug: uasc 1/1: res: OK (0x0)
debug: uasc 1/1: recv *ua.OpenSecureChannelResponse
debug: sending *ua.OpenSecureChannelResponse to handler
debug: uasc 1/1: send *ua.CreateSessionRequest with 247 bytes
debug: conn 1: recv MSGC with 8181 bytes
debug: uasc 1/1: recv MSGC with 8181 bytes
debug: conn 1: recv MSGC with 8181 bytes
debug: uasc 1/1: recv MSGC with 8181 bytes
debug: conn 1: recv MSGC with 8181 bytes
debug: uasc 1/1: recv MSGC with 8181 bytes
debug: conn 1: recv MSGF with 8180 bytes
debug: uasc 1/1: recv MSGF with 8180 bytes
debug: uasc 1/1: res: OK (0x0)
debug: uasc 1/1: recv *ua.CreateSessionResponse
debug: sending *ua.CreateSessionResponse to handler
debug: uasc 1/2: send *ua.ActivateSessionRequest with 149 bytes
debug: conn 1: recv MSGF with 96 bytes
debug: uasc 1/2: recv MSGF with 96 bytes
debug: uasc 1/2: res: OK (0x0)
debug: uasc 1/2: recv *ua.ActivateSessionResponse
debug: sending *ua.ActivateSessionResponse to handler
debug: uasc 1/3: send *ua.ReadRequest with 290 bytes
debug: conn 1: recv MSGF with 150 bytes
debug: uasc 1/3: recv MSGF with 150 bytes
debug: uasc 1/3: res: OK (0x0)
debug: uasc 1/3: recv *ua.ReadResponse
debug: sending *ua.ReadResponse to handler
debug: uasc 1/4: send *ua.BrowseRequest with 158 bytes
debug: conn 1: recv MSGF with 72 bytes
debug: uasc 1/4: recv MSGF with 72 bytes
debug: uasc 1/4: res: OK (0x0)
debug: uasc 1/4: recv *ua.BrowseResponse
debug: sending *ua.BrowseResponse to handler
debug: uasc 1/5: send *ua.BrowseRequest with 158 bytes
debug: conn 1: recv MSGF with 645 bytes
debug: uasc 1/5: recv MSGF with 645 bytes
debug: uasc 1/5: res: OK (0x0)
debug: uasc 1/5: recv *ua.BrowseResponse
debug: sending *ua.BrowseResponse to handler
debug: uasc 1/6: send *ua.ReadRequest with 250 bytes
debug: conn 1: recv ERRF with 101 bytes
debug: uasc 1/6: Decoding halted because of invalid data in the stream. StatusBadDecodingError (0x80070000)
debug: Received error: Decoding halted because of invalid data in the stream. StatusBadDecodingError (0x80070000)
browse children: Decoding halted because of invalid data in the stream. StatusBadDecodingError (0x80070000)
exit status 1

**Comment by magiconair** [comment]
Have a look at https://github.com/gopcua/opcua/issues/281#issuecomment-535436455.
