### ISSUE TITLE
Is this a client-only implementation, or has an OPC-UA server as well?

### ISSUE THREAD

**Issue by drasko** [gopcua/opcua#295]
I have seen [here](https://github.com/open62541/open62541/wiki/List-of-Open-Source-OPC-UA-Implementations) that Go `opcua` is a client-only lib.

However, I can see [this file](https://github.com/gopcua/opcua/blob/master/server.go) and [this example](https://github.com/gopcua/opcua/blob/master/examples/server/server.go) (where for some reasone most is commented-out), and I am wondering if this is a server library as well?

What is the state of the OPC-UA server implementation, and what is the use of branch `feature/server`?

**Comment by magiconair** [comment]
There was some server code in the original implementation but that was very basic. We are working on a server implementation which is what is in the branch you’ve mentioned. You’re more than welcome to help out.

**Comment by drasko** [comment]
@magiconair thanks a lot for the info. Closing this issue.
