### ISSUE TITLE
Client methods cause a panic if called without an established connection

### ISSUE THREAD

**Issue by fouwels** [gopcua/opcua#297]
The client methods throw a panic if you call them without a successful connect() prior, this should really be checked for and returned as an error. Otherwise connection states have to be managed by the consumer.

You can recreate this by removing the `connect()` call from your [read.go](https://github.com/gopcua/opcua/blob/master/examples/read/read.go) example.

See: https://gist.github.com/kaelanfouwels/83d04dad71a565595aa1ad13e3445be8

Results in, as it's lacking a session:
```
panic: interface conversion: interface {} is nil, not *opcua.Session

goroutine 1 [running]:
github.com/gopcua/opcua.(*Client).Session(0xc0000fe1c0, 0x0)
	/home/kf/go/pkg/mod/github.com/gopcua/opcua@v0.1.6/client.go:228 +0x8a
github.com/gopcua/opcua.(*Client).sendWithTimeout(0xc0000fe1c0, 0x5e2140, 0xc000094f90, 0x2540be400, 0xc0000a7d18, 0x0, 0x0)
	/home/kf/go/pkg/mod/github.com/gopcua/opcua@v0.1.6/client.go:447 +0x43
github.com/gopcua/opcua.(*Client).Send(0xc0000fe1c0, 0x5e2140, 0xc000094f90, 0xc0000a7d18, 0x0, 0x0)
	/home/kf/go/pkg/mod/github.com/gopcua/opcua@v0.1.6/client.go:439 +0x76
github.com/gopcua/opcua.(*Client).Read(0xc0000fe1c0, 0xc000094f90, 0x0, 0x0, 0x0)
	/home/kf/go/pkg/mod/github.com/gopcua/opcua@v0.1.6/client.go:496 +0x44a
main.main()
	/home/kf/proj/opcuatest/panic.go:36 +0x427
```

Would much rather the client methods return a typed error which can be checked upstream.

References: https://github.com/gopcua/opcua/pull/265 I've tested this in the latest version, still has the same issue.

**Comment by magiconair** [comment]
This has been fixed in #353
