### ISSUE TITLE
no matching versions for query "latest"

### ISSUE THREAD

**Issue by darlandieterich** [gopcua/opcua#315]
Why dont work for me when run example?

`go run examples/datetime/datetime.go -endpoint opc.tcp://localhost:4840`

ERROR:
> no matching versions for query "latest"

**Comment by magiconair** [comment]
What server are you testing with?

—
Frank Schröder

**Comment by darlandieterich** [comment]
Hi @magiconair, well, I'm beginner with opcua. I'm testing with `go run examples/server/server.go -endpoint opc.tcp://localhost:4840` 
but the message fail show: 

> cannot load github.com/gopcua/opcua/id: no matching versions for query "latest"

**Comment by darlandieterich** [comment]
Sorry, I'm wrong,  I'm using go v1.11 and for this case necessary update my golang to v1.13, and generate again the script.

it would be interesting to add in the readme a minimum requirement for go version v1.13

**Comment by magiconair** [comment]
Ah, the server code in gopcua is not implemented yet.

**Comment by magiconair** [comment]
Will update the README.
