### ISSUE TITLE
How to parse ua.AttributeIDDataTypeDefinition

### ISSUE THREAD

**Issue by goodspeed1986** [gopcua/opcua#329]
How to parse ua.AttributeIDDataTypeDefinition from array of attributes? What type of variable is it?
`attrs, err := n.Attributes(ua.AttributeIDNodeClass, ua.AttributeIDBrowseName, ua.AttributeIDDescription, ua.AttributeIDAccessLevel, ua.AttributeIDDataType, ua.AttributeIDDataTypeDefinition)`

**Comment by magiconair** [comment]
Hi @goodspeed1986 , maybe this snippet from the `browse` example helps:

https://github.com/gopcua/opcua/blob/master/examples/browse/browse.go#L54-L75
