### ISSUE TITLE
hosted godoc does not contain documentation for the new monitor package

### ISSUE THREAD

**Issue by jskelcy** [gopcua/opcua#343]
I imagine it is as simple as regenerating the documentation assets and pushing them to wherever the godoc is hosted, but I am not sure of the details. The new `monitor` package seems great and it would be nice to have all the documentation in one place.

**Comment by magiconair** [comment]
Which new `monitor` package are you referring to? Is that still on a branch/PR? 

This one?

https://godoc.org/github.com/gopcua/opcua/monitor

**Comment by jskelcy** [comment]
Wow, sorry about this. I did not realize how godoc lays out sub-packages, I was expecting to see all of the exposed types on the top level. While I think this would be nice for quickly searching the documentation, that is more of an issue with godoc then gopcua. 

Thanks for the quick response and I will close this out.
