### ISSUE TITLE
Exception while running browse example ver 0.1.11 against kepware v6 opcua server

### ISSUE THREAD

**Issue by axlev** [gopcua/opcua#347]
Hello,

Trying to run browse demo:
alex@alex-ThinkPad-T470p:~/go/pkg/mod/github.com/gopcua/opcua@v0.1.11$ go run examples/browse/browse.go -debug -node='ns=0;i=3048' -endpoint opc.tcp://192.168.14.77:49320
debug: Connect to opc.tcp://192.168.14.77:49320
debug: conn 1: start HEL/ACK handshake
debug: conn 1: sent HELF with 61 bytes
debug: conn 1: recv ACKF with 28 bytes
debug: conn 1: recv &uacp.Acknowledge{Version:0x0, ReceiveBufSize:0xffff, SendBufSize:0xffff, MaxMessageSize:0x1000000, MaxChunkCount:0x1388}
debug: uasc 1/1: send *ua.OpenSecureChannelRequest with 132 bytes
debug: conn 1: recv OPNF with 135 bytes
debug: uasc: OPN Request
debug: uasc 1/1: set secure channel id to 358883404
debug: uasc 1/1: recv OPNF with 135 bytes
debug: uasc 1/1: res: OK (0x0)
debug: uasc 1/1: recv *ua.OpenSecureChannelResponse
debug: sending *ua.OpenSecureChannelResponse to handler
debug: received security token tokenID: 1, createdAt: 2020-05-10 15:30:23.2012083 +0000 UTC, lifetime 3600000
debug: uasc 1/1: send *ua.CreateSessionRequest with 228 bytes
debug: conn 1: recv MSGF with 3226 bytes
debug: uasc 1/1: recv MSGF with 3226 bytes
debug: uasc 1/1: res: OK (0x0)
debug: uasc 1/1: recv *ua.CreateSessionResponse
debug: sending *ua.CreateSessionResponse to handler
debug: uasc 1/2: send *ua.ActivateSessionRequest with 117 bytes
debug: conn 1: recv MSGF with 96 bytes
debug: uasc 1/2: recv MSGF with 96 bytes
debug: uasc 1/2: res: OK (0x0)
debug: uasc 1/2: recv *ua.ActivateSessionResponse
debug: sending *ua.ActivateSessionResponse to handler
debug: uasc 1/3: send *ua.ReadRequest with 168 bytes
debug: conn 1: recv MSGF with 95 bytes
debug: uasc 1/3: recv MSGF with 95 bytes
debug: uasc 1/3: res: OK (0x0)
debug: uasc 1/3: recv *ua.ReadResponse
debug: sending *ua.ReadResponse to handler
debug: uasc 1/4: send *ua.CloseSessionRequest with 63 bytes
debug: conn 1: recv MSGF with 52 bytes
debug: uasc 1/4: recv MSGF with 52 bytes
debug: uasc 1/4: res: OK (0x0)
debug: uasc 1/4: recv *ua.CloseSessionResponse
debug: sending *ua.CloseSessionResponse to handler
debug: uasc 1/5: send *ua.CloseSecureChannelRequest with 57 bytes
debug: conn 1: close
debug: Connection closed
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x4f6f56]

goroutine 1 [running]:
github.com/gopcua/opcua/ua.(*Variant).ArrayLength(...)
	/home/alex/go/pkg/mod/github.com/gopcua/opcua@v0.1.11/ua/variant.go:97
github.com/gopcua/opcua/ua.(*Variant).String(0x0, 0xc00001a6a0, 0xa)
	/home/alex/go/pkg/mod/github.com/gopcua/opcua@v0.1.11/ua/variant.go:461 +0x26
main.browse(0xc000109e00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x14, 0xc000094760, 0x100000000203000)
	/home/alex/go/pkg/mod/github.com/gopcua/opcua@v0.1.11/examples/browse/browse.go:79 +0x938
main.main()
	/home/alex/go/pkg/mod/github.com/gopcua/opcua@v0.1.11/examples/browse/browse.go:188 +0x411
exit status 2

Please help me to figure out:
Is there anything wrong with the way I am trying to run it?
Is there more stable release ?

Thanks,
Alex

**Comment by kung-foo** [comment]
Kepware is not returning a value when reading the `Description` attribute of the initial node.

A simple check to see if the value is not nil prevents the panic:

```diff
diff --git a/examples/browse/browse.go b/examples/browse/browse.go
index 6310693..c2848a1 100644
--- a/examples/browse/browse.go
+++ b/examples/browse/browse.go
@@ -76,7 +76,9 @@ func browse(n *opcua.Node, path string, level int) ([]NodeDef, error) {
 
        switch err := attrs[2].Status; err {
        case ua.StatusOK:
-               def.Description = attrs[2].Value.String()
+               if attrs[2].Value != nil {
+                       def.Description = attrs[2].Value.String()
+               }
        case ua.StatusBadAttributeIDInvalid:
                // ignore
        default:
```
