### ISSUE TITLE
Subscribe to multiple nodeID at examples/subscribe.go

### ISSUE THREAD

**Issue by 78planet** [gopcua/opcua#356]
Can I subscribe to multiple nodeID at examples/subscribe.go?
I want to subscribe multiple nodes in one file.

**Comment by 78planet** [comment]
It is possible to receive multiple nodeID as shown below.
`go run subscribe.go -endpoint opc.tcp://localhost:4840 -node 'ns=1;s=Counter' -node 'ns=1;s=Sawtooth`

```
type arrayFlags []*string

func (i *arrayFlags) String() string {
	return "my string representation"
}

func (i *arrayFlags) Set(value string) error {
	*i = append(*i, &value)
	return nil
}

var nodeIDarr arrayFlags

flag.Var(&nodeIDarr, "node", "node id to subscribe to")

```

The code below is wrapped in a for statement.
```	
var miCreateRequest *ua.MonitoredItemCreateRequest
var eventFieldNames []string
for _, nodeID := range nodeIDarr {
	id, err := ua.ParseNodeID(*nodeID)
	if err != nil {
		log.Fatal(err)
	}

	if *event {
		miCreateRequest, eventFieldNames = eventRequest(id)
	} else {
		miCreateRequest = valueRequest(id)
	}
	res, err := sub.Monitor(ua.TimestampsToReturnBoth, miCreateRequest)
	if err != nil || res.Results[0].StatusCode != ua.StatusOK {
		log.Fatal(err)
	}
	go sub.Run(ctx) // start Publish loop
}
```
Solved easily.

**Comment by 78planet** [comment]
Using the above code, you can print data from multiple nodes.
Data of multiple nodes is output. But I don't know the data of a specific node.
Is there a way to know the data of a specific node from multiple data?

**Comment by kung-foo** [comment]
Hi @78planet, you might want to look at the higher level monitor interface: https://pkg.go.dev/github.com/gopcua/opcua@v0.1.11/monitor?tab=doc and https://github.com/gopcua/opcua/tree/master/examples/monitor

This abstracts away some of the complexity of the lower level subscription requirements (e.g. manually providing distinct "handles" for each subscribed item).

**Comment by 78planet** [comment]
Thank you @kung-foo, It was very helpful.
