### ISSUE TITLE
Add go-fuzz

### ISSUE THREAD

**Issue by zemirco** [gopcua/opcua#37]
This is just a reminder to use https://github.com/dvyukov/go-fuzz to test our parsers before releasing version 1.0.

**Comment by magiconair** [comment]
@zemirco Are you interested in setting this up?

**Comment by zemirco** [comment]
First of all, thank you for maintaining this project. It looks awesome :smiley: I think you're doing a great job.

Our second daughter was born two months ago. The first one is 2 1/2 years old. At the moment I don't have the time to contribute to this project. Sorry about that.

**Comment by magiconair** [comment]
@zemirco Congrats. I know how that is. Enjoy the time with your kids. I'll close this then for now.
