### ISSUE TITLE
[Subscribe] question about handle

### ISSUE THREAD

**Issue by ymmemo** [gopcua/opcua#375]
Hello
I am trying to subscribe to more nodes.
But I have a question about examples/subscribe/subscribe.go
`handle:= uint32(42)`
what does 42 mean? Can I assign another number?

**Comment by unknownet** [comment]
To be confirmed, but from what I understand the `handle` is an identifier that the client use to mark a `monitoredItem`.
The server send multiple unsorted `DataChangeNotification` and the only way to know from wich `monitoredItem` the  `DataChangeNotification` came from, is to compare their `handle`.

Note: the `handle` has to be unique (global) or you are going to mix up the notification, also the `handle` mechanism works well with a map (`map[uint32]*ua.NodeID` for instance) to identify the related NodeID.

You don't necessary have to know what is an handle if you use the API ["github.com/gopcua/opcua/monitor"]() instead, it contains an abstraction layer that take care of `handle` for you under the hood.

And to answer you question, yes you can assign any uint32 number.

**Comment by ymmemo** [comment]
@unknownet I see. thank you for your help : )
