### ISSUE TITLE
scheduleRenewal called only when SecurityMode is not MessageSecurityModeNone

### ISSUE THREAD

**Issue by axlev** [gopcua/opcua#396]
Hi,

I noticed that my session is disconnected every hour. I guess it is because of the fact that scheduleRenewal called only when SecurityMode is not MessageSecurityModeNone in method handleOpenSecureChannelResponse.

Can you please elaborate why this condition is required? I think that secure channel need to be renewed even in case the Message Security Mode is "None". 

What do you think?

Thanks.
Alex

**Comment by jbguerraz** [comment]
duplicates #392

**Comment by axlev** [comment]
Duplicates #392

**Comment by jbguerraz** [comment]
@alexlev2004  https://github.com/gopcua/opcua/blob/master/uasc/secure_channel.go#L600 looks like it's still there or am I missing something ?

**Comment by axlev** [comment]
> @alexlev2004 https://github.com/gopcua/opcua/blob/master/uasc/secure_channel.go#L600 looks like it's still there or am I missing something ?

Right, edited my comment right now
Thanks
