### ISSUE TITLE
ERR: The size of the message specified in the header is too large

### ISSUE THREAD

**Issue by axlev** [gopcua/opcua#399]
Subscribing for 3K nodes in single monitor causes an error

**Comment by magiconair** [comment]
Which version are you using?

**Comment by axlev** [comment]
v0.1.13

**Comment by magiconair** [comment]
We have merged some significant changes to master regarding subscriptions. Is it possible for you to try them and see if the error persists?

**Comment by magiconair** [comment]
FWIW, we are also not subscribing to all nodes at the same time. We are subscribing to 50 nodes at a time in a loop until all nodes are registered.

It is possible that depending on the node ids and the number of nodes you want to subscribe to you exceed the maximum size for a single message. 

Try to split this up in chunks of 50 or 100 nodes. This might also reduce the load on the OPC/UA server.

**Comment by axlev** [comment]
Yes if I split it works.
I tried to avoid concurrency and work around problems like #398 which seems having it's roots in thread safeness.

**Comment by axlev** [comment]
> We have merged some significant changes to master regarding subscriptions. Is it possible for you to try them and see if the error persists?

Sure. Testing it now and will update. Thanks for your support

**Comment by axlev** [comment]
Although can be done behind the scenes, we apply the workaround: split to separate monitors and subscribe for 50-100 items at once
