### ISSUE TITLE
Detect that the connection to the server is closed by timeout

### ISSUE THREAD

**Issue by hulakov** [gopcua/opcua#417]
I need to detect if the server is available i.e. need to handle an event when the connection is broken.
Is there any event that can help me? As far as I see `(s *SecureChannel) dispatcher()` doesn't generate any events when EOF received.
Another approach is to send some kind of ping message. But I cannot find an appropriate lightweight message

Thank you!

**Comment by hulakov** [comment]
I solved the issue via polling AttributeIDNodeID for node.

**Comment by magiconair** [comment]
What we do is to poll the server time on `i=2258` every second.
