### ISSUE TITLE
opcua subscribe failed opcua: invalid endpoint 

### ISSUE THREAD

**Issue by beyondyinjl2** [gopcua/opcua#420]
opcua addr: opc.tcp://192.168.3.16:53530/OPCUA/SimulationServer
opcua does not require certification
[https://github.com/gopcua/opcua/blob/master/examples/read/read.go](url)
read examples is ok, print the corresponding value
endpoint = flag.String("endpoint", "opc.tcp://192.168.3.16:53530/OPCUA/SimulationServer", "OPC UA Endpoint URL")
nodeID   = flag.String("node", "ns=5;s=aaa", "NodeID to read")

[https://github.com/gopcua/opcua/blob/master/examples/subscribe/subscribe.go](url)
subscribe examples failed:
endpoint = flag.String("endpoint", "opc.tcp://192.168.3.16:53530/OPCUA/SimulationServer", "OPC UA Endpoint URL")
		policy   = flag.String("policy", "None", "Security policy: None, Basic128Rsa15, Basic256, Basic256Sha256. Default: auto")
		mode     = flag.String("mode", "None", "Security mode: None, Sign, SignAndEncrypt. Default: auto")
		certFile = flag.String("cert", "", "Path to cert.pem. Required for security mode/policy != None")
		keyFile  = flag.String("key", "", "Path to private key.pem. Required for security mode/policy != None")
		nodeID   = flag.String("node", "ns=5;s=aaa", "node id to subscribe to")
		event    = flag.Bool("event", false, "subscribe to node event changes (Default: node value changes)")
		interval = flag.String("interval", opcua.DefaultSubscriptionInterval.String(), "subscription interval")
Print error:
* http://opcfoundation.org/UA/SecurityPolicy#None MessageSecurityModeNone https://PC-20200714DVPZ:53443/OPCUA/SimulationServer
opcua: invalid endpoint https://PC-20200714DVPZ:53443/OPCUA/SimulationServer
exit status 1

This line c := opcua.NewClient(ep.EndpointURL, opts...)
Replaced with c := opcua.NewClient(*endpoint, opts...) is ok

**Comment by magiconair** [comment]
I think this is due to the fact that the OPC/UA server is advertising an address under which it *cannot* be reached. We have seen this in one of our setups as well but still think this is a config error on the UA server.
