### ISSUE TITLE
opcua subscribe no data is generated

### ISSUE THREAD

**Issue by beyondyinjl2** [gopcua/opcua#421]
[https://github.com/gopcua/opcua/blob/master/examples/subscribe/subscribe.go](url)
subscribe examples:
Print log
 * http://opcfoundation.org/UA/SecurityPolicy#None MessageSecurityModeNone
Created subscription with id 5

Modify the value of opcua nodeId, the nodeId of subscribe does not push data over

**Comment by magiconair** [comment]
which version are you using?

**Comment by beyondyinjl2** [comment]
Use v0.2.0-rc1 version, that's it
