### ISSUE TITLE
How to reconnect after opcua is disconnected

### ISSUE THREAD

**Issue by beyondyinjl2** [gopcua/opcua#422]
The opcua collection program collects data after a normal connection. After the opcua service is suddenly shut down, the opcua collection program loses the connection. After the opcua service returns to normal, how to automatically reconnect.
The error is as follows:
write tcp 192.168.3.40:57545->192.168.3.48:53530: write: broken pipe
An error is reported when calling, Client.Connect(ctx):
opcua: already connected

**Comment by magiconair** [comment]
The 0.2.0-rc1 version on master should automatically reconnect.

**Comment by czwen** [comment]
Hello @magiconair 
Should i renew the client(or what should i do) after reconnect successfully?
It still can't read value when state become connected from reconnecting.

2023/03/22 11:51:12 Read failed: %s write tcp 127.0.0.1:57007->127.0.0.1:4840: write: broken pipe
2023/03/22 11:51:12 write tcp 127.0.0.1:57007->127.0.0.1:4840: write: broken pipe

**Comment by magiconair** [comment]
@czwen reconnect works for us but there is a challenge in using registered node ids. Please open an issue with an example program where this fails.
