### ISSUE TITLE
Server disconnection issues

### ISSUE THREAD

**Issue by axlev** [gopcua/opcua#436]
In case server was disconnected without RST/FIN, and reconnecting after ~5 mins, following issues could randomly be observed :
With `AutoReconnect==true`:
1. Getting multiple errors from the gopcua lib e.g.:
 "sub 9: next sequence number 97457 not in retransmission buffer [33509 33869 50317 66100 82224]"
 
2. Getting multiple errors through subscription channel: 
"opcua: handle 2 not found"

3. Just stopping getting any messages even when server is reconnected and the OPC sending updates - it is just not coming into the client code via subscription channel. In this case it the gopcua library continues getting updates from OPC server but does not pass it to the subscribed client code.

With AutoReconnect==false:
The client STUCK with following debug logs:

```
debug: publish: notAcked=[]
debug: publish: sub 714: notif: 98
debug: publish: pendingAcks=[{"SubscriptionID":714,"SequenceNumber":98}]
debug: publish: PublishRequest: {"RequestHeader":null,"SubscriptionAcknowledgements":[{"SubscriptionID":714,"SequenceNumber":98}]}
debug: uasc 1/3305: send *ua.PublishRequest with 74 bytes
debug: uasc readChunk EOF
debug: publish: PublishResponse: null
debug: publish: eof: pausing publish loop
debug: client: monitor: disconnected
debug: client: monitor: auto-reconnect disabled
debug: client: monitor: done
debug: sub: error: EOF
debug: sub: pause
debug: sub: pause: ctx.Done()
debug: sub: done
```

I think best solution for this could be propagating the error to the custom client code so it could decide what to do next, probably reconnect or `os.Exit()`.

**Comment by magiconair** [comment]
@alexlev2004 since you submitted this one in March 2021 I assume that you've tested this with one of the v0.2.0-rcX builds which had some race conditions. Could you test whether you still see the same issues with v0.2.3 and re-open? I am not seeing this behavior in our production env and when doing some tests with the python test server.
