### ISSUE TITLE
How to start the opc server ?

### ISSUE THREAD

**Issue by mjrlgue** [gopcua/opcua#437]
I downloaded the package with the `go` command, when I want to run the server with  ` go run server.go`, I get the following error: `go run: cannot run non-main package`, I can't find a well-explained doc of how to start the server properly, can someone point me to the right doc or command pls ?

**Comment by magiconair** [comment]
The server had not been implemented yet. Only the client package works

**Comment by Duell10111** [comment]
Is there some timeline or plans to implement the server?

**Comment by magiconair** [comment]
Not at this point. We had a couple of attempts but the biggest thing missing is the address space implementation.

**Comment by magiconair** [comment]
PRs are welcome of course :)

**Comment by heaxo** [comment]
@magiconair Hello, can the latest version achieve creating an Opcua server

**Comment by magiconair** [comment]
No. This is still work in progress —Frank SchröderOn 4 May 2023, at 04:05, heao ***@***.***> wrote:﻿
@magiconair Hello, can the latest version achieve creating an Opcua server
