### ISSUE TITLE
ua.MustVariant accepts arbitrary types including not `ua.ExtensionObject`

### ISSUE THREAD

**Issue by siscia** [gopcua/opcua#443]
The `ua.MustVariant` function seems to accept pretty much any type without complaining.

I thought it should accept only the type it know how to handle, basic types and ua.ExtensionsObject

```
package main

import (
	"fmt"

	"github.com/gopcua/opcua/ua"
)

type Foo struct {
}

func main() {
	ua.MustVariant(Foo{})
	fmt.Println("does not panic")
}
```

**Comment by magiconair** [comment]
Closed by #445.
