### ISSUE TITLE
msg.Value.String() returns empty string

### ISSUE THREAD

**Issue by mozesa** [gopcua/opcua#448]
Hello!

First, I would like to thank you implementing OPC UA protocol for go community.

I am at version: `v0.2.0-rc2` and I noticed that `msg.Value.String()` returns `""` using `monitor.go` example.

![image](https://user-images.githubusercontent.com/49973426/130630958-df781f1f-08f3-4052-bad1-2363191fbd7a.png)

Actually, I would like to achieve to have the string representation of all the values.

Thanks for your help in advance.

**Comment by magiconair** [comment]
Thank you!

I'm not sure I understand your question. Is the value a string and is it empty?

**Comment by mozesa** [comment]
I subscribed to `xSensor` and `iSensor`.
![image](https://user-images.githubusercontent.com/49973426/130632660-ffafcec0-1794-4db3-b920-5fd4ac10dede.png)

`msg.Value.Value()` works fine and gives me: `true`, `11` but the types are `interface{}`. 

What is the purpose of the `msg.Value.String()` function?
I thought that it should return the `string` representation of any type instead of `interface{}`.

**Comment by magiconair** [comment]
Yeah, it should probably do that but right now it returns the string value if the variant type is string or string-like. To achieve what you want you could do `fmt.Sprintf("%v", msg.Value.Value())`

https://github.com/gopcua/opcua/blob/main/ua/variant.go#L472-L491

**Comment by mozesa** [comment]
Thanks! I actually do that 😄
