### ISSUE TITLE
invalid value: opcua: cannot set variant to int

### ISSUE THREAD

**Issue by mozesa** [gopcua/opcua#449]
Hello!

I have run into the following error message: `invalid value: opcua: cannot set variant to int`.

I used the `write.go` example.
The `iSensor` node, as you can see, has an `INT` type.

(_Btw, setting the the value of `xSensor` works fine, with `ua.NewVariant(true)`._)

I am using [Codesys](https://www.codesys.com/) soft PLC.

![image](https://user-images.githubusercontent.com/49973426/130645568-1b6a9b32-f3fe-41b3-912c-3133f033b5fb.png)

gopcua: `v0.2.0-rc2`
golang: `1.17`

Thanks for your help in advance.

**Comment by magiconair** [comment]
yes, `int` and `uint` are not supported since they are platform dependent. Use any of the other types like `int32` or `uint16`

**Comment by magiconair** [comment]
`int` and `uint` are either 32 or 64 bit depending on the CPU architecture.

**Comment by mozesa** [comment]
Thanks for your help.
I leave it for the future.
![image](https://user-images.githubusercontent.com/49973426/130650553-2369b3ea-54e8-40a6-ba6c-6a8910e52db1.png)
