### ISSUE TITLE
Error handling in ActivateSession breaks reconnecting logic if the server is restarted or the session is invalid

### ISSUE THREAD

**Issue by diericd** [gopcua/opcua#474]
Hi,

I've encountered an issue in the handling of the Response in ActivateSession: 

https://github.com/gopcua/opcua/blob/affd2bf105fe37786d69cd3607b5f7ed085f8c90/client.go#L694-L699

If c.CloseSession() returns StatusBadSessionIDInvalid the new session will not be activated and the reconnection logic goes into an infinite loop (this can happen if the opc-server is restarted and the previous session is no longer known by the server).  

I understand the attempt of closing the previous session but must the closing succeed in for ActivateSession to be a success? 

eg:

```
...
return c.sechan.SendRequest(req, s.resp.AuthenticationToken, func(v interface{}) error {
		var res *ua.ActivateSessionResponse
		if err := safeAssign(v, &res); err != nil {
			return err
		}

		// save the nonce for the next request
		s.serverNonce = res.ServerNonce

		c.CloseSession()

		c.session.Store(s)
		return nil
	})
```

**Comment by magiconair** [comment]
I am not sure if we have really tested the reconnection logic enough to ensure that it works as intended. So I guess we are doing that now. The double close issues point in the same direction that there is something fishy. Lets get our heads around this.

**Comment by magiconair** [comment]
The only thing I could think of is that we create too many new sessions since we don't properly close the old ones. But I'm happy to try this approach.
