### ISSUE TITLE
Refactor Needed: Subscription.Monitor()

### ISSUE THREAD

**Issue by salmanazmat666** [gopcua/opcua#491]
In [Subscription.Monitor()](https://github.com/gopcua/opcua/blob/6e89091fa1796dc72a5dcbab39e4082522cf43c7/subscription.go#L107), if one of the monitored items returns bad status code, the function just [returns there](https://github.com/gopcua/opcua/blob/6e89091fa1796dc72a5dcbab39e4082522cf43c7/subscription.go#L126), discarding all of the other items even if their status code is good. This creates conflict in the state of subscription present in server and subscription stored in client. Since server will store the good items discarding the bad ones, while client discards all the items if just one is bad.
The server will continue to send the notifications for the good items it stored, but the client is now receiving notifications for items that don't exist in the client's subscription.

My suggestion would be that the Subscription.Monitor() stores the good items while discarding the bad ones, and it should return the MonitoredItemsResponse if atleast one item is good.

If any error occurs which is not related to individual items like `serverDisconnected` etc, return `nil, error`.
In all other cases, return `res, nil`.

**Comment by magiconair** [comment]
Yes, this got into the initial v0.2.0 code unnoticed and is causing trouble for us as well. It also changes behavior in comparison to v0.1.13. I'll create a PR to remove the check since you can inspect the `CreateMonitoredItemsResponse` if you care for the status of individual nodes just like you could before.
