### ISSUE TITLE
Could not resolve address ...

### ISSUE THREAD

**Issue by mozesa** [gopcua/opcua#494]
Dear **@magiconair**,

I would like to ask for your help.
I have the following error message: `could not resolve address tben-lx-plc:4840`

I have enclosed an image which depicts the endpoints, which contains 6 endpoints.
The problem that endpoints[0] always gives the error: `could not resolve ...`.
But I could use endpoints[3] to connect successfully.

Is there any method by which I can filter out endpoints which EndpointURL like "tben-lx-plc".

![image](https://user-images.githubusercontent.com/49973426/140735879-7ea5a915-4e80-41e0-b22e-170c5c9edeaf.png)

Thanks for your help in advance.

**Comment by kung-foo** [comment]
It's pretty common for an opc-ua server to just return the hostname of itself. That may or may not be resolvable as is by your client. Sometime you need to append a domain. Sometimes it returns a private name.

**Comment by mozesa** [comment]
I see! But is there a standard way to be able to connect to such an OPC UA server?

**Comment by kung-foo** [comment]
For our applications at my company, we rarely, if ever, use the `GetEndpoints` API. Or if we do, we _don't_ trust/use the hostname since it is not configured properly most of the time.

**Comment by kung-foo** [comment]
In your case, it depends whether `tben-lx-plc` is the same as `192.168.0.21`

**Comment by mozesa** [comment]
Yes, it is the same.
What should I use instead? - `opcua.NewClient`?!

**Comment by kung-foo** [comment]
Yes, this is what I use 99% of the time.

**Comment by mozesa** [comment]
Thanks for the advice - it works!
