### ISSUE TITLE
An invalid node ID error is reported after the read.go command is executed

### ISSUE THREAD

**Issue by spatxos** [gopcua/opcua#511]
Kepware
```
V6.9.572.0
```
![image](https://user-images.githubusercontent.com/29770198/143162740-0ad505ac-3a49-44db-b317-77adc7fab2ca.png)
![image](https://user-images.githubusercontent.com/29770198/143162777-a1c98ff2-7f5c-480d-add8-07c4f891fb7e.png)
The Softing OPC UA Client reads data correctly
![image](https://user-images.githubusercontent.com/29770198/143162797-0e807517-8cf5-4b66-bd0d-60b7621d8930.png)

However, an invalid node ID error was reported. 
```
>go run examples/read/read.go -endpoint opc.tcp://localhost:49320 -node 'ns=0;i=2262'

>invalid node id: opcua: invalid node id: 'ns=0;i=2262'
exit status 1

>go run examples/read/read.go -endpoint opc.tcp://localhost:49320 -node ' ns=0;i=2262 '

>Status not OK: The node id refers to a node that does not exist in the server address space. StatusBadNodeIDUnknown (0x80340000)，TimestampsToReturnBoth: TimestampsToReturnBoth
exit status 1
```

![image](https://user-images.githubusercontent.com/29770198/143168456-9442e550-d900-48db-90f3-c37256f71fa8.png)
![image](https://user-images.githubusercontent.com/29770198/143168628-45a77c2d-7637-4170-899c-e79c21090ecd.png)

**Comment by magiconair** [comment]
Try reading just `i=2262`

**Comment by kung-foo** [comment]
Also in your second invocation there are spaces before and after the node id. The node id parser is pretty strict, so probably won't handle that.

**Comment by magiconair** [comment]
`ns=0;` shouldn't matter...

https://github.com/gopcua/opcua/blob/main/ua/node_id_test.go#L143

Also, good point about the spaces. @kung-foo we should add test cases for this. Do you think it is worth to trim spaces in `ParseNodeID` ?

**Comment by spatxos** [comment]
Using ```i=2262``` is still an error,
```
>go run examples/read/read.go -endpoint opc.tcp://localhost:49320 -node 'i=2262'

>Status not OK: The node id refers to a node that does not exist in the server address space. StatusBadNodeIDUnknown (0x80340000)，TimestampsToReturnBoth: TimestampsToReturnBoth
exit status 1
```
![image](https://user-images.githubusercontent.com/29770198/143202796-6e0cfb68-c580-4b5b-b262-824224dc163f.png)

**Comment by kung-foo** [comment]
Are you able to read `i=2258` (current time)?

**Comment by spatxos** [comment]
> Are you able to read `i=2258` (current time)?

Reading ```i=2258``` is the same error message, but I can get the time using ```datetime.go```

```
>go run examples/read/read.go -endpoint opc.tcp://localhost:49320 -node 'i=2258'

>Status not OK: The node id refers to a node that does not exist in the server address space. StatusBadNodeIDUnknown (0x80340000)，TimestampsToReturnBoth: TimestampsToReturnBoth
exit status 1
```
![image](https://user-images.githubusercontent.com/29770198/143329908-afac760d-eca6-4c6b-8a7e-93d61fc741ba.png)
```
>go run examples/datetime/datetime.go -endpoint opc.tcp://localhost:49320

>* http://opcfoundation.org/UA/SecurityPolicy#None MessageSecurityModeNone
2021-11-25 00:31:01.1735585 +0000 UTC
```
![image](https://user-images.githubusercontent.com/29770198/143329846-7f1867ef-7060-492d-a327-eb77fb777fe6.png)

The ```TimestampsToReturnBoth``` is different, ```Both``` in ```read.go``` and ```Source``` in ```datetime.go```

**Comment by spatxos** [comment]
# ```read.go```
并且，在读取 ```Object/Server``` 目录下的Node Id时，在KepServer中将会输出 ```ActivateSessionRequest,ActivateSessionResponse,ReadRequest,ReadResponse``` 一共四条日志，但是在读取 ```Object/channel1/equip1``` 目录下的Node Id时，在KepServer中只会输出 ```ActivateSessionRequest,ActivateSessionResponse``` 一共两条日志 
![image](https://user-images.githubusercontent.com/29770198/143332162-8751d0d2-8731-4ccb-b345-847449a5e2f3.png)

# The ```Object/Server``` directory reads logs
```ActivateSessionRequest```
![image](https://user-images.githubusercontent.com/29770198/143332253-c2a401c0-2888-4c0a-84de-bc32073a7c0f.png)
```ActivateSessionResponse```
![image](https://user-images.githubusercontent.com/29770198/143332263-c581a3f6-fae6-4b30-80cf-d037625e8cb2.png)
```ReadRequest```
![image](https://user-images.githubusercontent.com/29770198/143332271-04ac87e2-fc65-42f2-8264-d306ab8d6742.png)
```ReadResponse```
![image](https://user-images.githubusercontent.com/29770198/143332275-77538bdb-9bb7-4049-b805-f166c7b375a1.png)

# The ```Object/channel1/equip1``` directory reads logs
```ActivateSessionRequest```
![image](https://user-images.githubusercontent.com/29770198/143333034-0e534c67-ee4f-4b9a-9de4-f008fbe46d46.png)
```ActivateSessionResponse```
![image](https://user-images.githubusercontent.com/29770198/143333098-2022c75e-04d4-4d0a-ad57-3f0b4b42167d.png)

  # ```datetime.go```
Six records were generated when read using ```datetime.go```,They are respectively ```ActivateSessionRequest, ActivateSessionResponse, ReadRequest ReadResponse, CloseSessionRequest, CloseSessionResponse```
```ActivateSessionRequest```
![image](https://user-images.githubusercontent.com/29770198/143333437-c4228938-883e-415d-96f1-bebb19dcb2e7.png)
```ActivateSessionResponse```
![image](https://user-images.githubusercontent.com/29770198/143333446-f1ded2b9-f5fd-41d2-84d5-1eb411afcb4c.png)
```ReadRequest```
![image](https://user-images.githubusercontent.com/29770198/143333449-76ca2b82-4b8b-4616-ad99-66577c90cf54.png)
```ReadResponse```
![image](https://user-images.githubusercontent.com/29770198/143333456-f211d1db-5b69-4be6-8da0-ce1aa9b4fead.png)
```CloseSessionRequest```
![image](https://user-images.githubusercontent.com/29770198/143333472-cc93340f-a214-4912-a5fd-cefe34af8bd5.png)
```CloseSessionResponse```
![image](https://user-images.githubusercontent.com/29770198/143333464-c9cc8586-2fb9-47cb-9a9c-575590d010f7.png)

**Comment by magiconair** [comment]
In the read.go example the dump shows `s='i=2258'` which means it is trying to read the node as a string node id which cannot work of course. 

Did you modify the examples in any way?

**Comment by magiconair** [comment]
<img width="159" alt="image" src="https://user-images.githubusercontent.com/229005/143398757-7d894173-3114-4505-9f1d-c7d28c465fe8.png">

**Comment by magiconair** [comment]
Terminal 1:
```sh
> ./uatest/method_server.py
cryptography is not installed, use of crypto disabled
cryptography is not installed, use of crypto disabled
Endpoints other than open requested but private key and certificate are not set.
Listening on 0.0.0.0:4840
```

Terminal 2:
```sh
> git describe
v0.2.2
> go run ./examples/read/read.go  -node 'i=2258'
time.Date(2021, time.November, 25, 7, 39, 29, 558650000, time.UTC)
```

**Comment by spatxos** [comment]
Now the data can be obtained through the command box of ```git```, why can't it be obtained by using the ```cmd``` command box of the windows system
![6496371a7798a40ff4eee29deb4423a](https://user-images.githubusercontent.com/29770198/143510956-e9a339b0-5686-405f-ba52-d1d380ed615a.png)

**Comment by magiconair** [comment]
Can you try to use `-node "i=2258"`? I think the windows shell does not remove the single quotes.

**Comment by spatxos** [comment]
Yes, double quotes will work, thank you
```
>go run examples/read/read.go -endpoint opc.tcp://localhost:49320 -node "i=2262"

"urn:LAPTOP-B5F5AJI1:Kepware.KEPServerEX.V6:UA%20Server"
```
![image](https://user-images.githubusercontent.com/29770198/143540380-0e0d96f6-3806-4150-b97b-d91e3ba42510.png)
