### ISSUE TITLE
Update namespaces array when reconnecting

### ISSUE THREAD

**Issue by cailloumajor** [gopcua/opcua#547]
Hello, and thank you for your work on this project.
I am writing a proxy to allow subscribing to OPC-UA nodes realtime updates via [Centrifugo](https://centrifugal.dev/): https://github.com/cailloumajor/opcua-centrifugo
I currently explore about how to use namespace URL, I read the code and also https://github.com/gopcua/opcua/pull/512. This got me to a question: shouldn't the client cached namespaces array be refreshed in the reconnection process ?
I would be happy to submit a PR if needed.

**Comment by magiconair** [comment]
Yes, I think that's a good idea. PR would be welcome.

**Comment by magiconair** [comment]
It was easy to add. @cailloumajor could you test if this works for you?
