### ISSUE TITLE
How can I guarantee the monitor data order？

### ISSUE THREAD

**Issue by flykarry** [gopcua/opcua#560]
![image](https://user-images.githubusercontent.com/14309127/155469799-6d1fc435-1077-4c97-a670-83c9c712d2c8.png)
Is there any method to get the nodeId string  ?

**Comment by tekulvw** [comment]
+1 on this, are we guaranteed that the monitored items in the data change notification matches the order in which items were added to monitor? Does this hold true across all number of monitor and unmonitor calls?

**Comment by tekulvw** [comment]
After doing a bit of digging, it appears that the "clientHandle" you set when creating a new monitored item request is the intended method to link a MonitoredItem back to it's associated node:
<img width="765" alt="image" src="https://user-images.githubusercontent.com/3731082/155644701-d993314e-7299-43bd-a912-8eb790e475e1.png">
<img width="366" alt="image" src="https://user-images.githubusercontent.com/3731082/155644755-b106e716-4a08-427a-b85a-de54d2f23446.png">

**Comment by flykarry** [comment]
> After doing a bit of digging, it appears that the "clientHandle" you set when creating a new monitored item request is the intended method to link a MonitoredItem back to it's associated node: <img alt="image" width="765" src="https://user-images.githubusercontent.com/3731082/155644701-d993314e-7299-43bd-a912-8eb790e475e1.png"> <img alt="image" width="366" src="https://user-images.githubusercontent.com/3731082/155644755-b106e716-4a08-427a-b85a-de54d2f23446.png">

but in my example, I monitor 3 point with 1 clienthandle, the MonitoredItem is not sorted when I debug the code, in other words maybe I will receive not sorted array when the network is unstable

**Comment by magiconair** [comment]
The clientHandle needs to be different for every monitored item. You use it to map back to the node. Check the subscription monitor. It should do something like this. The order is not guaranteed.

**Comment by flykarry** [comment]
> The clientHandle needs to be different for every monitored item. You use it to map back to the node. Check the subscription monitor. It should do something like this. The order is not guaranteed.

Ok, It works. Thanks for your reply
