### ISSUE TITLE
[HELP] Import information model to server

### ISSUE THREAD

**Issue by xujiesh0510** [gopcua/opcua#604]
Hi. is there any way to import  information model  (a nodeset2.xml file )  to server    ?
Do I have to write it mannually?
The open source OPC UA Stack open62541 and c# stack   support  reading NodeSet2.xml format and can initialize its address space with the predefined nodes. With this you can easily start an OPC UA server offering your custom nodeset.
 
tutorial  link:
https://opcua.rocks/custom-information-models/

 nodeset2.xml  looks like this:

```

<?xml version="1.0" encoding="utf-8"?>
<UANodeSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://opcfoundation.org/UA/2011/03/UANodeSet.xsd">
  <NamespaceUris>
    <Uri>http://opcfoundation.org/BatchPlant</Uri>
  </NamespaceUris>
  <Models>
    <Model ModelUri="http://opcfoundation.org/BatchPlant">
      <RequiredModel ModelUri="http://opcfoundation.org/UA/" XmlSchemaUri="http://opcfoundation.org/UA/2008/02/Types.xsd" />
    </Model>
  </Models>
  <Aliases>
    <Alias Alias="Boolean">i=1</Alias>
   .....
 
 
  </Aliases>
  <UAObject NodeId="ns=1;i=1" BrowseName="1:工厂" SymbolicName="allfactory">
    <DisplayName>工厂</DisplayName>
    <Description>Contains all instances of animals</Description>
    <References>
      <Reference ReferenceType="Organizes" IsForward="false">i=85</Reference>
      <Reference ReferenceType="HasTypeDefinition">i=58</Reference>
    </References>
  </UAObject>
  <UAObjectType NodeId="ns=1;i=2" BrowseName="1:CustomEvent">
    <DisplayName>CustomEvent</DisplayName>
    <References>
      <Reference ReferenceType="HasProperty">ns=1;i=13</Reference>
      <Reference ReferenceType="HasSubtype" IsForward="false">i=2133</Reference>
    </References>
  </UAObjectType>
```

thanks

**Comment by piperoc** [comment]
@xujiesh0510  you flagged this as completed, but there is no answer to your original questions. Did you resolve this? It doesn't look like there is a NodeSet import facility... it would be very nice. Thanks for expanding on this.

**Comment by danomagnum** [comment]
The newest commits of the [server branch ](https://github.com/gopcua/opcua/tree/server) has an ImportNodeSet function on the server object.

You can see an example of it in the base server initialization logic where it imports the base opc ua nodeset from an embedded nodeset2.xml file.

(note that schema.OpcUaNodeSet2 is the []bytes from the xml file)

https://github.com/gopcua/opcua/blob/c449b7ce33904016dd76ec6f2a0aa798cded7ee4/server/server.go#L145-L153

I haven't tested it with other nodeset files but if you give it a try, let me know if it works or not.

**Comment by xujiesh0510** [comment]
> @xujiesh0510 you flagged this as completed, but there is no answer to your original questions. Did you resolve this? It doesn't look like there is a NodeSet import facility... it would be very nice. Thanks for expanding on this.

finally，I had to  use open62541 ,which is a C library. other languages' implementaion is not fully supported.
