### ISSUE TITLE
subscription example always fails after 60 seconds

### ISSUE THREAD

**Issue by zskevind** [gopcua/opcua#609]
Hi buddy!
I tried to subscribe some items from the Prosys Simulation Server, using the latest examples/subsribe.go, with option as below:
**go run examples/subscribe/subscribe.go -endpoint opc.tcp://uademo.prosysopc.com:53530/OPCUA/SimulationServer -node "ns=3;i=1001" -mode None -debug True**

but after some successfuly responses, the program failed with following messages:
```
debug: publish: notAcked=[]
debug: publish: notif: 56
debug: publish: pendingAcks=[{"SubscriptionID":1115,"SequenceNumber":56}]
debug: publish: PublishRequest: {"RequestHeader":null,"SubscriptionAcknowledgements":[{"SubscriptionID":1115,"SequenceNumber":56}]}
debug: uasc 2/63: send *ua.PublishRequest with 106 bytes
MonitoredItem with client handle 42 = 11
debug: uasc 2: Close()
debug: publish: PublishResponse: null
debug: publish: error: unexpected error. Do we need to stop the publish loop?: context canceled
debug: sub: error: context canceled
debug: sub: ctx.Done()
debug: sub: done
debug: client: monitor: done
debug: uasc 2/66: send *ua.CloseSecureChannelRequest with 57 bytes
debug: uacp 2: close
debug: uasc 2: readChunk EOF
```

I also tried with the local server installed on my own laptop, the error still lives.

**Comment by magiconair** [comment]
Does the value change? Sounds like session timeout. Try subscribing to `i=2258` (current time)

**Comment by zskevind** [comment]
> Does the value change? Sounds like session timeout. Try subscribing to `i=2258` (current time)

Yes, I also did this, leads to the same error,here is the debugging messages:

```
debug: uasc 2/62: send *ua.PublishRequest with 106 bytes
MonitoredItem with client handle 42 = 2022-10-07 04:18:48.395 +0000 UTC
debug: uacp 2: recv MSGF with 140 bytes
debug: uasc 2/62: recv MSGF with 140 bytes
debug: uasc 2/62: recv *ua.PublishResponse
debug: uasc 2/62: sending *ua.PublishResponse to handler
debug: publish: PublishResponse: {"ResponseHeader":{"Timestamp":"2022-10-07T04:18:49.396Z","RequestHandle":62,"ServiceResult":0,"ServiceDiagnostics":{"EncodingMask":0,"SymbolicID":0,"NamespaceURI":0,"Locale":0,"LocalizedText":0,"AdditionalInfo":"","InnerStatusCode":0,"InnerDiagnosticInfo":null},"StringTable":null,"AdditionalHeader":{"EncodingMask":0,"TypeID":{"NodeID":"i=0","NamespaceURI":"","ServerIndex":0},"Value":null}},"SubscriptionID":1172,"AvailableSequenceNumbers":[56],"MoreNotifications":false,"NotificationMessage":{"SequenceNumber":56,"PublishTime":"2022-10-07T04:18:49.396Z","NotificationData":[{"EncodingMask":1,"TypeID":{"NodeID":"i=811","NamespaceURI":"","ServerIndex":0},"Value":{"MonitoredItems":[{"ClientHandle":42,"Value":{"EncodingMask":13,"Value":{},"Status":0,"SourceTimestamp":"2022-10-07T04:18:49.396Z","SourcePicoseconds":0,"ServerTimestamp":"2022-10-07T04:18:49.396Z","ServerPicoseconds":0}}],"DiagnosticInfos":null}}]},"Results":[0],"DiagnosticInfos":null}
debug: publish: notAcked=[]
debug: publish: notif: 56
debug: publish: pendingAcks=[{"SubscriptionID":1172,"SequenceNumber":56}]
debug: publish: PublishRequest: {"RequestHeader":null,"SubscriptionAcknowledgements":[{"SubscriptionID":1172,"**SequenceNumber":56**}]}
MonitoredItem with client handle 42 = 2022-10-07 04:18:49.396 +0000 UTC
debug: uasc 2/63: send *ua.PublishRequest with 106 bytes
debug: uasc 2: Close()
debug: client: monitor: done
debug: publish: PublishResponse: null
debug: publish: error: unexpected error. Do we need to stop the publish loop?: context canceled
debug: sub: error: context canceled
debug: sub: pause
debug: sub: pause: ctx.Done()
debug: sub: done
debug: uasc 2/66: send *ua.CloseSecureChannelRequest with 57 bytes
debug: uacp 2: close
debug: uasc 2: readChunk EOF
```

As you see, the last successful response sequence is 56, and then fail.



========================================================================

I found a real production opcua server, and subscribed to i=2258, but there is no suprise, also failed after 59 successful responses.

**Comment by magiconair** [comment]
I think it's because of the way the example is written. There is a 60 sec timeout in the code that isn't very obvious. I think I stumbled over this as well. 

https://github.com/gopcua/opcua/blob/main/examples/subscribe/subscribe.go#L35-L39

**Comment by zskevind** [comment]
Sorry, I'm so stupid that I missed the important code snippet of the example;
```

	// add an arbitrary timeout to demonstrate how to stop a subscription
	// with a context.
	d := 60 * time.Second
	ctx, cancel := context.WithTimeout(context.Background(), d)
	defer cancel()
```

**Comment by magiconair** [comment]
Yeah, it's not obvious if you don't specifically look for it. I think none of the other examples are like this. We should probably log this to make this more obvious.

**Comment by zskvd** [comment]
> 

Lol, 😂.   I found the problem at the time when you figure out the real problem!

**Comment by magiconair** [comment]
I'll add a log line. :)

**Comment by zskevind** [comment]
> I think it's because of the way the example is written. There is a 60 sec timeout in the code that isn't very obvious. I think I stumbled over this as well.
> 
> https://github.com/gopcua/opcua/blob/main/examples/subscribe/subscribe.go#L35-L39


Lol, 😂.   I found the problem at the time when you figure out the real problem!

Realy appreciate your help!!!

**Comment by magiconair** [comment]
https://github.com/gopcua/opcua/commit/3618f0ec0fcc2f33ad91303374404bb6daa8e44a

**Comment by magiconair** [comment]
Can you have a look whether this makes it obvious enough? It's on `main`

**Comment by zskevind** [comment]
> Can you have a look whether this makes it obvious enough? It's on `main`
<img width="814" alt="image" src="https://user-images.githubusercontent.com/20521961/194505690-8cc25f48-9f0d-4305-b08e-eeabd1fd957a.png">
I think it's not very obvious, if the server is fast enough, all the messages flashed through the screen . May be you can give  some pause time after this log message appears.😄
