### ISSUE TITLE
log.Fatal called when a certificate fails to load

### ISSUE THREAD

**Issue by jrtitus** [gopcua/opcua#616]
This causes any process using gopcua/opcua to exit without warning and is caused by either the referenced file not existing, or a decoding failure. 

Can it be handled more cleanly like logging an error and returning? Or perhaps returning `(Option, error)` from `CertificateFile`?

https://github.com/gopcua/opcua/blob/3618f0ec0fcc2f33ad91303374404bb6daa8e44a/config.go#L268-L271

It looks like the same thing happens in the `RemoteCertificateFile`, `PrivateKeyFile`, and `setCertificate` functions as well. I also see TODO comments in `AuthAnonymous` and `AuthUsername` questioning the use of `Fatal`. My suggestion would be no.

**Comment by magiconair** [comment]
Eh, `log.Fatal` in a library is never OK. Sorry about that. Will fix.

```sh
$ ack -l log.Fatal | grep -v examples
cmd/status/main.go
cmd/id/main.go
cmd/service/main.go
config.go
```

**Comment by magiconair** [comment]
Ah, I remember why I did this 3y ago. No good option to bubble up errors for config options. I'll rework the config option.

**Comment by jrtitus** [comment]
> Ah, I remember why I did this 3y ago. No good option to bubble up errors for config options. I'll rework the config option.

Awesome. Thank you very much for following up so quickly on this.

**Comment by magiconair** [comment]
So we have two options to solve this:

1. We bubble the error up during `Dial` and/or `Connect` which does not require us to change any API
2. We change `NewClient` to return an error which breaks all existing code. Cleaner but more disruptive.
3. We do 1. until v0.5.0 where we have to break the API anyway and then update `NewClient`.

I'm for option 3. @kung-foo any opinion?

**Comment by kung-foo** [comment]
3 is fine by me

**Comment by jrtitus** [comment]
Hi @magiconair. Just curious - when do you plan to make the `v0.3.8` release?

**Comment by magiconair** [comment]
sorry, dropped the ball here.

**Comment by magiconair** [comment]
@jrtitus done.

**Comment by jrtitus** [comment]
> sorry, dropped the ball here.

No worries!

> done

Thanks! :)
