### ISSUE TITLE
Add contributing guidelines

### ISSUE THREAD

**Issue by wmnsk** [gopcua/opcua#62]
For those who is interested in contribution, we need to provide guideline.

- [ ] Consider what it should be like
- [ ] Write docs in `CONTRIBUTING.md`
  * (Optional) Add `ISSUE_TEMPLATE.md`
  * (Optional) Add `PULL_REQUEST_TEMPLATE.md`
- [ ] ...

**Comment by magiconair** [comment]
I would not overthink this. Lets first get some more contributors before we set rules of engagement.

**Comment by magiconair** [comment]
Same here. Right now we have 1-2 active contributors. Lets first try to gain some traction and have this project not got the way of the Dodo 🐦
