### ISSUE TITLE
OpenSecureChannelRequest return readChunk EOF

### ISSUE THREAD

**Issue by whutwxn** [gopcua/opcua#625]
I connect to INOVANCE PLC,
go to step:uasc 1/1: send *ua.OpenSecureChannelRequest with 132 bytes
It return : debug: uasc 1: readChunk EOF
I compared the request packets sent by gopcua and Ua Expert application using wireshark, and the screenshot is as follows:
gopcua:
![image](https://user-images.githubusercontent.com/44281071/208574913-5a84ffb4-cac3-46aa-b3df-9932bcc15266.png)
Ua Expert:
![image](https://user-images.githubusercontent.com/44281071/208575177-32d37533-2a03-4c38-8085-c3850a50918a.png)

the Ua Expert send 133bytes with the clientnonce=0x00,but gopcua send 132bytes without clientonce.
Is it the gopcua`s bug or is it the PLC`s bug?

**Comment by whutwxn** [comment]
when i add some code to the secure_channel.go line 533:

```go
	if len(localNonce) == 0 {
		var bt []byte
		bt = append(bt, 0x00)
		localNonce = bt
	}
```

it works!

**Comment by kung-foo** [comment]
similar issue: https://github.com/FreeOpcUa/python-opcua/issues/393

**Comment by kung-foo** [comment]
My initial read of this is that this is a bug in the OPC-UA server.

**Comment by kung-foo** [comment]
Can you try the following patch:

```patch
diff --git a/uapolicy/securitypolicy.go b/uapolicy/securitypolicy.go
index 3b30933..d211aa9 100644
--- a/uapolicy/securitypolicy.go
+++ b/uapolicy/securitypolicy.go
@@ -148,7 +148,11 @@ func (e *EncryptionAlgorithm) NonceLength() int {
 }
 
 func (e *EncryptionAlgorithm) MakeNonce() ([]byte, error) {
-       b := make([]byte, e.NonceLength())
+       l := e.NonceLength()
+       if l == 0 {
+               return nil, nil
+       }
+       b := make([]byte, l)
        // note: we use `rand.Reader` instead of `rand.Read(...)` to ensure that we don't accidentally switch to using
        // math/rand (which has a default, fixed seed). Only crypto/rand exposes a global `io.Reader` var.
        _, err := io.ReadFull(rand.Reader, b)
```

This will send a `null` bytestring nonce versus an empty (zero-length) bytestring.

**Comment by whutwxn** [comment]
ok,thanks

**Comment by magiconair** [comment]
@whutwxn Does that mean the fix worked?
