### ISSUE TITLE
Adding the benthos-umh docker container to "Companies using it in production"

### ISSUE THREAD

**Issue by JeremyTheocharis** [gopcua/opcua#646]
Hi, 

I am Jeremy, Co-Founder and CTO of the United Manufacturing Hub. Based on this library, we wrote a plugin for benthos (www.benthos.dev), which allows to easily extract data out of OPC-UA servers, normalize and process them and send them to the "Unified Namespace" (MQTT / Kafka). 

Would you be interested in linking to that Docker container in your README? https://github.com/united-manufacturing-hub/benthos-umh

You could also include the "United Manufacturing Hub" (www.umh.app) as a company using it in production. Please confirm, then I could prepare a PR.

Regards,
Jeremy

**Comment by magiconair** [comment]
Yes. That would be nice. You can create a PR adding you to the Users section. We can also remodel that a bit if you can come up with a better design.

**Comment by sruehl** [comment]
@magiconair I think this one can be close as #647 has been merged?
