### ISSUE TITLE
How can i get every nodeid when use batch list to read?

### ISSUE THREAD

**Issue by CHN-STUDENT** [gopcua/opcua#650]
Hi, now i have i question, i try to read opc data by using batchlist, but when i try to parse datas, i do not know which data from original nodeid, so could you tell me how can i get its original nodeid?

```
if len(resp.Results) > 0 {
  for _, item := range resp.Results {
    // how can i get every item's original nodeid?
  }
}
```

**Comment by kung-foo** [comment]
The `resp.Results` slice will be the same length and order as the request. See: https://github.com/gopcua/opcua/blob/v0.3.13/examples/read/read.go#L41-L43. So `NodesToRead[0]` is returned in `resp.Results[0]`.

**Comment by CHN-STUDENT** [comment]
Thanks! And i have anthoer question, how much nodeIDs List i can get maximum on once get?

And if i want to subscribe a nodeIDs List, how can i do？

**Comment by kung-foo** [comment]
Depends on the OPC-UA server. I usually just chunk the node list before sending read requests.

Regarding subscriptions, check out:

https://github.com/gopcua/opcua/blob/main/examples/subscribe/subscribe.go
https://github.com/gopcua/opcua/blob/main/examples/monitor/monitor.go

**Comment by CHN-STUDENT** [comment]
OK, i try to use page slice to deal with nodeIDs List, thanks for your help!
