### ISSUE TITLE
Problem with using ReferencedNodes

### ISSUE THREAD

**Issue by sruehl** [gopcua/opcua#682]
When using `ReferencedNodes` new Nodes will be created using the `NodeID` of a `ExpandedNode`. This `NodeID` has flags for namespace and server which (the values as we use Node not ExpandedNode) then are not passed when using those Nodes
```golang
// ReferencedNodes returns the nodes referenced by this node.
func (n *Node) ReferencedNodes(ctx context.Context, refs uint32, dir ua.BrowseDirection, mask ua.NodeClass, includeSubtypes bool) ([]*Node, error) {
	if refs == 0 {
		refs = id.References
	}
	var nodes []*Node
	res, err := n.References(ctx, refs, dir, mask, includeSubtypes)
	if err != nil {
		return nil, err
	}
	for _, r := range res {
		nodes = append(nodes, n.c.Node(r.NodeID.NodeID))
	}
	return nodes, nil
}
```
here you can see the problematic line: `nodes = append(nodes, n.c.Node(r.NodeID.NodeID))`

So I have a server which responds with that on a `BrowseRequest` call:
`UA Secure Conversation Message: BrowseRequest`
![image](https://github.com/gopcua/opcua/assets/1769155/f2a5982b-3972-4596-af81-9a39f9a7785f)
When using then those nodeIDs for read it produces a invalid request because of the flags and the server returns a error:
`UA Secure Converation Message[Malformed Packet]`
![image](https://github.com/gopcua/opcua/assets/1769155/1bfab331-5877-487a-a1da-6a06b14be07a)
here in the request above you can see that the flags `c0` are set from the retrieved `ExpandedNode`
`ErrorMessage`
![image](https://github.com/gopcua/opcua/assets/1769155/0fe200d2-81bb-4d3d-b675-cbcc6cd800f7)

**Comment by sruehl** [comment]
@magiconair could it be that this [todo](https://github.com/gopcua/opcua/blob/main/ua/node_id.go#L16) is the root cause?
node_id.go:16 "`// todo(fs): fix mask`"

**Comment by sruehl** [comment]
https://github.com/gopcua/opcua/pull/683 fixes the issue

**Comment by kung-foo** [comment]
@sruehl is there overlap with the issue described here? https://github.com/gopcua/opcua/pull/619

**Comment by sruehl** [comment]
I think it is basically the same Problem. Although I like the way #619 is a bit more efficient I would prefer having a `NodeFromExpandedNode` factory function which copies the values and set's the mask like it is done in #619. The function there called `RemoveExpandedFlag` doesn't make much sense outside the copy scenario. My approach does that externals so the `NodeFromExpandedNode` would be more efficient because it has access to the private fields. I could update the PR with that suggestion if wanted.

**Comment by sruehl** [comment]
my approach == #683
