### ISSUE TITLE
[Question] How to connect opcua server By UaExpert

### ISSUE THREAD

**Issue by Ri0nGo** [gopcua/opcua#750]
The NodeSet2_server and node_server packages in the example directory start a server program, and I use UaExpert to connect to the server, and the connection fails, is there any configuration that needs to be added?

This UaExpert connect config
![图片](https://github.com/user-attachments/assets/808beca4-4c04-485b-9c46-27e4fec6a11d)
![图片](https://github.com/user-attachments/assets/5f5168b9-6dab-4667-80de-38d15565974e)
Then, I click ignore, log is BadConfigurationError.
![图片](https://github.com/user-attachments/assets/4a3d7601-a54a-4f15-95d2-b00e1ac362c3)

Looking forward to your reply, many thanks!

**Comment by danomagnum** [comment]
Seems to work for me.  Can you do a wireshark capture while trying to connect?

If possible, could you also try connecting with python and let me know how that goes?

```
>>> import opcua
cryptography is not installed, use of crypto disabled
cryptography is not installed, use of crypto disabled
>>> client = opcua.Client('opc.tcp://localhost:4840')
>>> client.connect()
Requested session timeout to be 3600000ms, got 0ms instead
>>> root = client.get_root_node()
>>> root.get_children()
[Node(TwoByteNodeId(i=85)), Node(TwoByteNodeId(i=86)), Node(TwoByteNodeId(i=87))]
>>> 
```

**Comment by Ri0nGo** [comment]
Sorry for taking so long to get back to you. I reinstalled UaExpert and it connects fine.
I'm very sorry to disturb you.

**Comment by Ri0nGo** [comment]
solved
