### ISSUE TITLE
[v0.6.1] unnecessary log entry in secure_channel sendAsyncWithTimeout

### ISSUE THREAD

**Issue by lyimmi** [gopcua/opcua#760]
Hi everyone,

I tried the new version v0.6.1, everything look good, but unfortunately there is a log statement in [secure_channel line:1036 - sendAsyncWithTimeout](https://github.com/gopcua/opcua/blame/74c8438b6c82b0e448c9b9a89e141a62796b339c/uasc/secure_channel.go#L1036). It is not critical but it's littering in our central logging system, with every call.

If it is okay to remove I'm happy to make a pull request.

Thanks!

**Comment by danomagnum** [comment]
Yeah, looks like that was a debugging log that got left in and could be removed without issue.
