### ISSUE TITLE
Open the Wiki

### ISSUE THREAD

**Issue by zemirco** [gopcua/opcua#79]
Hey,

I tried adding some stuff to the wiki. Looks like it's not activated or I'm not allowed to use it. Could you change that?

Today I experimented with gopcua in the browser. I have a working example compiling it to webassembly and decoding raw messages in the browser.

The idea is to use gopcua in the browser and communicate with OPC UA servers that support websockets.

**Comment by wmnsk** [comment]
I think it’s open to everyone according to the settings.
I opened a default wiki, so could you try it again?

![b82f1d06-02c3-428c-9dde-eac96709a92a](https://user-images.githubusercontent.com/6134010/45754058-8c7c5280-bc55-11e8-86e8-73c879f7a023.png)

**Comment by zemirco** [comment]
I can see the wiki now but I cannot add content.

![screenshot from 2018-09-19 14-55-04](https://user-images.githubusercontent.com/1132354/45754462-0b549980-bc1c-11e8-8dda-59f2f0c92cda.png)

**Comment by zemirco** [comment]
I'll try creating a new page locally and push it via git. wait a second.

**Comment by wmnsk** [comment]
Ah I’ve overlooked the second checkbox in settings. 
Can you try on web again?

**Comment by zemirco** [comment]
yes it works! thx
